version: '3'

includes:
    go: taskfiles/Taskfile_go.yml
    git: taskfiles/Taskfile_git_tag.yml
    
tasks:

  default:
    desc: lists available tasks
    silent: true
    cmds:
      - task --list-all

  install:
    desc: installs package from github as CLI
    silent: true
    cmds:
      - echo "To work, the github repo must be public"
      - go install github.com/vdmitriyev/lenvs@latest
  
  run:
    desc: runs package
    silent: true
    cmds:
      - go run main.go

  run-list:
    desc: runs `--command list` of the packacge
    silent: true
    cmds:
      - go run . --command list
      
  version:
    desc: prints current version of the packacge
    silent: true
    cmds:
      - go run . --version